### ISSUE TITLE
Access/link to the publications

### ISSUE THREAD

**Issue by adriguir** [dynawo/dynawo.github.io#76]
In the publications page, in addition to the titles and references of the publications, it would be nice to have a direct link to the papers or presentations themselves.

@gautierbureau if I remember well, we didn't really want to have pdf stored somewhere on the websites. Which option seems possible? 
One possibility would be to make a link to my researchgate profile where the pdfs are uploaded but if any better option, just let me know.

**Comment by gautierbureau** [comment]
One option is to create a tag, upload the pdf as assets and use the direct link to those assets

**Comment by adriguir** [comment]
Finally, I chose to just add a link to the Dynawo project page on researchgate. It seems to be enough in my opinion at the moment.
